#!/usr/bin/env bash

set -Eeuo pipefail -o posix

esd="${1}"
tmpdir=$(mktemp -d)

if command -v brew &>/dev/null; then
  brew install wimlib
fi

__cleanup() {
  rm -rf "${tmpdir}"
}
trap __cleanup EXIT

image_count=$(wiminfo "${esd}" --header | grep '^Image Count' | cut -d= -f 2)

wimapply "${esd}" 1 "${tmpdir}"
wimexport "${esd}" 2 "${tmpdir}/sources/boot.wim" --compress=LZX --chunk-size 32K
wimexport "${esd}" 3 "${tmpdir}/sources/boot.wim" --compress=LZX --chunk-size 32K --boot

for index in $(seq 4 "${image_count}"); do
  wimexport "${esd}" "${index}" "${tmpdir}/sources/install.esd" --compress=LZMS --chunk-size 128K
done

basename="$(basename "${esd}" .esd)"
iso="${basename}.iso"

rm -f "${iso}"
hdiutil makehybrid -o "${iso}" -iso -udf -hard-disk-boot -eltorito-boot "${tmpdir}/efi/microsoft/boot/efisys.bin" -iso-volume-name ESD_ISO -udf-volume-name ESD-ISO "${tmpdir}"
