#!/bin/sh
#
# Copyright (c) 2023, 2024, 2025 Mattie Behrens.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR
# ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

# MARK: color support
# <https://mattiebee.dev/dye>

dye_detect() {
	command -v tput >/dev/null || return 1
	test -n "${NO_COLOR-}" && return 1
	test -n "${CLICOLOR_FORCE-}" && return
	test -t 1 || return 1
	test -n "${CLICOLOR-}" && return
	test "${1-}" = "default-off" && return 1
	return 0
}

dye_out() (
	_1="$1"
	_2="${2-}"
	test -n "$1" && shift
	test -n "${1-}" && shift
	if [ -z "${DYE_COLORS-}" ]; then
		printf "%s" "$*"
		return
	fi
	if [ -z "${_2}" ] || [ -z "${1-}" ]; then
		eval "tput ${_1}" || true
		return
	fi
	eval "tput ${_1}" || true
	printf "%s" "$*"
	eval "tput ${_2}" || true
)

dye_color() (
	case "$1" in
	black) echo 0 ;;
	red) echo 1 ;;
	green) echo 2 ;;
	yellow) echo 3 ;;
	blue) echo 4 ;;
	magenta) echo 5 ;;
	cyan) echo 6 ;;
	white | brightgray) echo 7 ;;
	gray) echo 8 ;;
	bright*)
		base="$(dye_color "${1##*bright}")"
		echo "$((8 + base))"
		;;
	'' | *[!0-9]*) return 1 ;;
	*) echo "$1" ;;
	esac
)

dye_synth() {
	if [ "${DYE_COLORS}" = "8" ] && [ "$1" -ge 8 ] && [ "$1" -le 15 ]; then
		echo $(($1 - 8))
		return 1
	fi
	echo "$1"
}

dye() {
	if [ "$1" = "setup" ]; then
		shift
		dye_detect "$@" && DYE_COLORS="$(tput colors)"
		return 0
	fi

	(
		_1="$1"
		shift
		case "${_1}" in
		fg)
			c="$(dye_color "$1")" || return
			c="$(dye_synth "${c}")" || dye_out bold
			shift
			dye_out "setaf ${c}" "sgr0" "$@"
			;;
		bg)
			c="$(dye_color "$1")" || return
			c="$(dye_synth "${c}")" || true
			shift
			dye_out "setab ${c}" "sgr0" "$@"
			;;
		dim) dye_out "dim" "sgr0" "$@" ;;
		bold) dye_out "bold" "sgr0" "$@" ;;
		reverse) dye_out "rev" "sgr0" "$@" ;;
		reset) dye_out "sgr0" ;;
		i | italic) dye_out "sitm" "ritm" "$@" ;;
		so | standout) dye_out "smso" "rmso" "$@" ;;
		u | ul | underline) dye_out "smul" "rmul" "$@" ;;
		begin) dye "$@" ;;
		end)
			case "$1" in
			i | italic) dye_out "ritm" ;;
			so | standout) dye_out "rmso" ;;
			u | ul | underline) dye_out "rmul" ;;
			*) return 1 ;;
			esac
			;;
		*)
			dye fg "${_1}" "$@"
			;;
		esac
	)
}

# MARK: user interface

print_task() { echo "$(dye green "==>") $(dye bold "$*")"; }
print_subtask() { echo "$(dye blue "==>") $(dye bold "$*")"; }
print_error() { echo "$(dye red "Error:") $*"; }
print_warning() { echo "$(dye yellow "Warning:") $*"; }

set -eu

dye setup

# MARK: preflight checks

script="$(basename "$0")"

if [ "$(uname)" != "Darwin" ]; then
	print_warning "$(dye bold "${script}") is currently for macOS and may not work here"
fi

if [ -z "${1-}" ] || [ "$1" = "-h" ]; then
	echo "$(dye red "Usage:") ${script} ESD"
	exit 0
fi

check_wimlib_tool() {
	if ! which "$1" >/dev/null; then
		print_error "wimlib tools not found"
		exit 1
	fi
}
check_wimlib_tool wiminfo
check_wimlib_tool wimapply
check_wimlib_tool wimexport

if ! which hdiutil >/dev/null; then
	print_error "hdiutil (a standard macOS tool) not found"
	exit 1
fi

esd="$1"

if [ ! -f "${esd}" ]; then
	print_error "$(dye green "${esd}") not found"
	exit 2
fi

# MARK: cleanup exit hook

tmpdir=$(mktemp -d)

__cleanup() {
	if [ -z "${NO_CLEANUP-}" ]; then
		print_task "Cleaning up $(dye green "${tmpdir}")"
		rm -rf "${tmpdir}"
	else
		print_warning "NO_CLEANUP was set; $(dye green "${tmpdir}") will not be removed"
	fi
}
trap __cleanup EXIT

# MARK: export images

print_task "Exporting images from $(dye green "${esd}")"

image_count=$(wiminfo "${esd}" --header | grep '^Image Count' | cut -d= -f 2)
if ! [ "${image_count}" -gt 0 ] 2>/dev/null; then
	print_error "could not get image count"
	exit 3
fi
echo "Found ${image_count} images."

print_subtask "Exporting image 1"
wimapply "${esd}" 1 "${tmpdir}"

print_subtask "Exporting image 2"
wimexport "${esd}" 2 \
	"${tmpdir}/sources/boot.wim" \
	--compress=LZX --chunk-size=32K

print_subtask "Exporting image 3"
wimexport "${esd}" 3 \
	"${tmpdir}/sources/boot.wim" \
	--compress=LZX --chunk-size=32K --boot

for index in $(seq 4 "${image_count}"); do
	print_subtask "Exporting image ${index}"
	wimexport "${esd}" "${index}" \
		"${tmpdir}/sources/install.esd" \
		--compress=LZMS --chunk-size 128K --recompress
done

# MARK: create ISO

basename="$(basename "${esd}" .esd)"
iso="${basename}.iso"

rm -f "${iso}"
print_task "Creating $(dye green "${iso}")"
hdiutil makehybrid \
	-o "${iso}" \
	-iso -udf \
	-hard-disk-boot -eltorito-boot "${tmpdir}/efi/microsoft/boot/efisys.bin" \
	-iso-volume-name ESD_ISO \
	-udf-volume-name ESD-ISO \
	"${tmpdir}"
